FROM golang:1.23-alpine AS builder
WORKDIR /app
COPY ./ ./
RUN go mod download
RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o chittychat-client ./client


FROM alpine:latest
WORKDIR /root/
COPY --from=builder /app/chittychat-client .
COPY chitty-chat-tls/server.crt ./
ENTRYPOINT ["./chittychat-client"]

