# Start from a Golang base image
FROM golang:1.23-alpine AS builder
WORKDIR /app
COPY ./ ./
RUN go mod download
RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o chittychat-server ./server

# Start a new stage from scratch
FROM alpine:latest  
WORKDIR /root/
COPY --from=builder /app/chittychat-server .
COPY chitty-chat-tls/server.crt chitty-chat-tls/server.key ./
EXPOSE 50051
CMD ["./chittychat-server"]
